import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import AnimatedBackground from "@/components/animated-background";
import ChatBot from "@/components/chat-bot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BumbleBee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html
        suppressHydrationWarning
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <body suppressHydrationWarning>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            forcedTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {/* Animated Background */}
            {/* Animated Background */}
            <AnimatedBackground />

            {/* Content */}
            <div className="relative z-10">
              {/* header */}
              <Header />
              <main className="min-h-screen">
                {children} <ChatBot />
              </main>
              <footer className="py-12 border border-b relative">
                <div className="container px-4 mx-auto text-center text-black">
                  <p>2025 BumbleBee. All Rights Reserved</p>
                </div>
              </footer>
            </div>

            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
